### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by cshaa** [datel-intellectus/darkbot#2]
# Milestone 1
## UX
 * [ ] **indikovat a vyžadovat počet volných bloků (2h)** – v levelech je omezeno, kolik bloků je možné použít, zatím to ale hra nevyžaduje
 * [ ] **systém dialogů a nápověd (~5h)** – instrukce, co je potřeba v levelech dělat, oznámení výhry atd.
 * [ ] **hezčí in-game menu (2h)** – „Exit, Start/Restart, Stop“
 * [ ] **hudba (1h)** – přidat hudbu pro menu a levely
 * [ ] **využít nový vzhled (?)** – současné podklady od grafika nejsou všechny stejně zarovnané, proto je obtížné je použít přímo

## Gameplay
 * [ ] **odemykání levelů (1h)** – levely budou zamčené a až po dokončení předchozích se odemknou
 * [ ] **win state (1h)** – hra detekuje splnění úkolů a oznámí výhru

## Level design
 * [ ] **darkbot (5h)** – základy algoritmizace, metody, rekurze

----

# Milestone 2
## UX
 * [ ] **animace (5h+)** – vizuální indikace akcí robota (chůze, skok, náraz do stěnuy atd); vyžaduje spolupráci s grafikem
 * [ ] **zvukové efekty (~1h)** – zvukové indikace akcí robota

## Gameplay
 * [ ] **oprava bugu vody (doufám, že méně než 10h)** – nevím, co problém způsobuje, proto je těžké odhadnout, jak dlouho zabere oprava; viz issue #1
 * [ ] **interakce vody a květin (1h)** – nerozkvetlé květiny rozkvetou v přítomnosti vody
 * [ ] **vztlak vody, plovoucí předměty (~2h)** – zní to poměrně jednoduše, ale může to vyžadovat náročný refactor kódu
 * [ ] **redesign algoritmu pro vodu, aby fungovaly spojené nádoby (10h+)**

## Level design
 * [ ] **waterbot (5h)** – interakce voda-květina, přehrady, vztlak, čekání, spojené nádoby

----

# Milestone 3
## UX
 * [ ] **systém entit (?)** – ryby, ptáci, jiskry elektřiny, ...
 * [ ] **přepínání mezi Jr. a Sr. bloky (~5h)** – v současnosti máme jenom bloky ze Scratch Jr.; přidat možnost programovat pomocí bloků z "dospělého" Scratche

## Gameplay
 * [ ] **simulace elektrických obvodů (10h+)** – už funguje systém skládání obvodů, ještě je potřeba simulovat, jak se bude chovat
 * [ ] **design nových elektrických prvků (~5h)** – tlačítka? žárovky? kondenzátory? – je potřeba vymyslet, jaké prvky jsou potřeba z pohledu level designu
 * [ ] **magnetismus a interakce s ostatními systémy (~2h)**

## Level design
 * [ ] **electrobot (?)** – elektrické obvody

----

# Milestone 4+
## Analýza
 * systém sbírání dat?
 * důkladný playtesting

## Budoucnost projektu
 * open-sourcing?
 * tvorba vlastních levelů?
 * modování?

# Gameplay
 * programování robotů v JavaScriptu/Typescriptu?

## Level design
 * **twinbots** – paralelizace, asynchronní programování, race condition
 * **gravitybot** – něco s gravitací?
 * **chembot** – chemické reakce?
 * stavění a boření bloků
